# 94

language: java

addons:
  apt:
    packages:
      - libcups2-dev
      - libx11-dev
      - libxext-dev
      - libxrender-dev
      - libxrandr-dev
      - libxtst-dev
      - libxt-dev
      - libasound2-dev
      - libffi-dev

os:
  - linux
  - osx

env:
  - BRANCH="lworld"
    HG_REPOSITORY="valhalla"
    REPOSITORY="valhalla"
    ARTIFACT="jdk-16-lworld"
    SCM="git"
  - BRANCH="vectorIntrinsics"
    HG_REPOSITORY="panama"
    REPOSITORY="dev"
    ARTIFACT="jdk-16-vector"
    SCM="hg"
  - BRANCH="nestmates"
    HG_REPOSITORY="valhalla"
    REPOSITORY="valhalla"
    ARTIFACT="jdk-16-nestmates"
  - BRANCH="fibers"
    HG_REPOSITORY="loom"
    REPOSITORY="loom"
    ARTIFACT="jdk-16-loom"
  - BRANCH="sealed-types"
    HG_REPOSITORY="amber"
    REPOSITORY="amber"
    ARTIFACT="jdk-16-sealed"
  - BRANCH="patterns-stage-2" 
    HG_REPOSITORY="amber"
    REPOSITORY="amber"
    ARTIFACT="jdk-16-pattern"

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source ./install-jdk.sh --feature 14
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ -z "$SCM" ]]; then export SCM="git" ; fi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ -z "$SCM" ]]; then export SCM="hg" ; fi ; fi

install:
  - source ./install-$SCM.sh

script:
  - chmod u+x ./build.sh
  - ./build.sh
#  - cat /home/travis/build/forax/java-next/loom/make/hs_err_*

before_deploy:
  - tar zcvf $ARTIFACT-$TRAVIS_OS_NAME.tar.gz $ARTIFACT

deploy:
  provider: releases
  api_key:
    secure: "R5ORaE8RpahzmQJrmu10ffhzduKHLMH50cQgdc7d6yZZ3yTyQHNcb/TWtqrjTrusfMkItGI/ydY/64wFBq9EiNbM9XCBQrqnRinCQ1+5LS60K8ZuHMDc7H9gQqIKi091rXtBl3YZDBJZOEHH+FsaJIf3hThYyPhug3Iyzd1/9mqUJr8xie8uiw7RJaHjp0c3zus1aOnHJUAz3L+EzM07IM6o/3IdgtYCDPZgLfNLTJg7L5d/R5x7i0j2QIVO8tFYalQQE/UC9E0EazRIyy5habIMRzdBrlcWdE3q4gFfXkk4S6iFRJ4y6Hfn+iaLCTRcamSyrjYVSGgv0HngEg83WYk0t1Jwm/OI2yCjCvKIhPyONrGlfHc6/H9IiE0Mks6cLoGcL+f4OrxpeKEv17kD79NMcif8EATrL+W6MXnkZ1bw6Mng7mM1t6cXi5uOF3Y3i0u2ELxXTHgpKPnYVFO8AZ9wPE8Tl72inrmEJPzUXoXeN1/DV1s4mbQemXVs8YPLYfuOB9lho5y9wJOLZgH+n8WfNA52SvyCr/cnJg/4Hj+KVfw56/RfyrlY4GqzXvivFuBovP3JmTscWDIZc2zcn7oEOmk2BRdim940CG5t/PHEj4YSUyR0SugotkBEP61qY4IgzRGqgG9Dy9N6VR59ZAYw2i/bpOZbeSp34tTDM64="
  file: $ARTIFACT-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: false   # avoid loop
  
