sudo: true

language: java
jdk: openjdk10

before_install:
  - unset _JAVA_OPTIONS

install:
  - sudo apt-get install build-essential
  - sudo apt-get install libfreetype6-dev
  - sudo apt-get install libcups2-dev
  - sudo apt-get install libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
  - sudo apt-get install libasound2-dev
  - sudo apt-get install libffi-dev
  - chmod u+x ./install.sh 
  - ./install.sh

script:
  - chmod u+x ./build.sh
  - ./build.sh

#before_deploy:
#  - cd target
#  - tar zcvf jdk-11-lworld.tar.gz

#deploy:
#  provider: releases
#  api_key:
#    secure: "???"
#  file: ???.tar.gz
#  skip_cleanup: true
#  on:
#    tags: true
