sudo: false

language: java
jdk: openjdk-ea

install:
- java --version
- bash ./install.sh

script:
- bash ./build.sh

#before_deploy:
#  - cd target
#  - tar zcvf jdk-11-lworld.tar.gz

#deploy:
#  provider: releases
#  api_key:
#    secure: "???"
#  file: ???.tar.gz
#  skip_cleanup: true
#  on:
#    tags: true
