sudo: true

language: java
jdk: openjdk11

before_install:
  - unset _JAVA_OPTIONS

os:
  - linux
  - osx

env:
  - LATEST_COMMIT="221983ae9e6b"
    HG_REPOSITORY="valhalla"
    REPOSITORY="valhalla"
    ARTIFACT="jdk-12-lworld"
  - LATEST_COMMIT="f18cac6e3214"
    HG_REPOSITORY="valhalla"
    REPOSITORY="valhalla"
    ARTIFACT="jdk-12-nestmates"
  - LATEST_COMMIT="4646340e9574"
    HG_REPOSITORY="loom"
    REPOSITORY="loom"
    ARTIFACT="jdk-12-loom"
  - LATEST_COMMIT="f78041dc7a0d"
    HG_REPOSITORY="amber"
    REPOSITORY="amber"
    ARTIFACT="jdk-12-amber"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libfreetype6-dev        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libcups2-dev            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libasound2-dev          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libffi-dev              ; fi
  
install:
  - chmod u+x ./install.sh 
  - ./install.sh

script:
  - chmod u+x ./build.sh
  - ./build.sh

before_deploy:
  - tar zcvf $ARTIFACT-$TRAVIS_OS_NAME.tar.gz $ARTIFACT

deploy:
  provider: releases
  api_key:
    secure: "R5ORaE8RpahzmQJrmu10ffhzduKHLMH50cQgdc7d6yZZ3yTyQHNcb/TWtqrjTrusfMkItGI/ydY/64wFBq9EiNbM9XCBQrqnRinCQ1+5LS60K8ZuHMDc7H9gQqIKi091rXtBl3YZDBJZOEHH+FsaJIf3hThYyPhug3Iyzd1/9mqUJr8xie8uiw7RJaHjp0c3zus1aOnHJUAz3L+EzM07IM6o/3IdgtYCDPZgLfNLTJg7L5d/R5x7i0j2QIVO8tFYalQQE/UC9E0EazRIyy5habIMRzdBrlcWdE3q4gFfXkk4S6iFRJ4y6Hfn+iaLCTRcamSyrjYVSGgv0HngEg83WYk0t1Jwm/OI2yCjCvKIhPyONrGlfHc6/H9IiE0Mks6cLoGcL+f4OrxpeKEv17kD79NMcif8EATrL+W6MXnkZ1bw6Mng7mM1t6cXi5uOF3Y3i0u2ELxXTHgpKPnYVFO8AZ9wPE8Tl72inrmEJPzUXoXeN1/DV1s4mbQemXVs8YPLYfuOB9lho5y9wJOLZgH+n8WfNA52SvyCr/cnJg/4Hj+KVfw56/RfyrlY4GqzXvivFuBovP3JmTscWDIZc2zcn7oEOmk2BRdim940CG5t/PHEj4YSUyR0SugotkBEP61qY4IgzRGqgG9Dy9N6VR59ZAYw2i/bpOZbeSp34tTDM64="
  file: $ARTIFACT-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: false   # avoid loop
  
